name: web3
description: web3dart wrapper.
version: 0.0.1
author: hhglory@outlook.com
homepage: https://github.com/better-dart/pkg

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  meta:

  # dart utils:
  dust:
    git:
      url: https://github.com/better-dart/pkg.git   # repo http clone url
      ref: "2ec4156"                                # git tag or git commit-id
      path: packages/dust                           # pkg path

  #
  #
  #
  bip39: ^1.0.3
  bip32: ^1.0.7

#  wallet_core:
#  wallet_core:
#    git:
#      url: https://github.com/better-dart/fuse_wallet_core.git
#      ref: hotfix-v2021-04-06      # commit id

  wallet_core:
    path: /Users/henry/Documents/iSpace/better-dart/fuse_wallet_core

#  web3dart:
#  web3dart:
#    git:
#      url: https://github.com/better-dart/web3dart.git
#      ref: hotfix-v1.2.3 # branch

  web3dart:
    path: /Users/henry/Documents/iSpace/better-dart/web3dart


dev_dependencies:
  flutter_test:
    sdk: flutter
  dotenv:
  flutter_dotenv:
  protobuf: ^1.1.0
  protoc_plugin:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
    - assets/icon/coin/ # 注意: 每个文件夹路径都要单独配置, 且要加/后缀, 特别蠢!
    - assets/icon/defi/

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
